server:
    port: 8080
    servlet:
        context-path: /setter
spring:
    config:
        import: conf/mysql.yml,conf/mybatis.yml
    mvc:
        pathmatch:
            matching-strategy: path_pattern_parser

my:
    secretKey: xiaoading03302116
