package com.example.dao.mapper;

import com.example.model.entity.Admin;
import com.example.model.entity.AdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrators
     *
     * @mbg.generated
     */
    long countByExample(AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrators
     *
     * @mbg.generated
     */
    int deleteByExample(AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrators
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer adminid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrators
     *
     * @mbg.generated
     */
    int insert(Admin row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrators
     *
     * @mbg.generated
     */
    int insertSelective(Admin row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrators
     *
     * @mbg.generated
     */
    List<Admin> selectByExample(AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrators
     *
     * @mbg.generated
     */
    Admin selectByPrimaryKey(Integer adminid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrators
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") Admin row, @Param("example") AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrators
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") Admin row, @Param("example") AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrators
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Admin row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrators
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Admin row);
}