package com.example.dao.mapper;

import com.example.model.entity.Installer;
import com.example.model.entity.InstallerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InstallerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table installers
     *
     * @mbg.generated
     */
    long countByExample(InstallerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table installers
     *
     * @mbg.generated
     */
    int deleteByExample(InstallerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table installers
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer installerid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table installers
     *
     * @mbg.generated
     */
    int insert(Installer row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table installers
     *
     * @mbg.generated
     */
    int insertSelective(Installer row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table installers
     *
     * @mbg.generated
     */
    List<Installer> selectByExample(InstallerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table installers
     *
     * @mbg.generated
     */
    Installer selectByPrimaryKey(Integer installerid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table installers
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") Installer row, @Param("example") InstallerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table installers
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") Installer row, @Param("example") InstallerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table installers
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Installer row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table installers
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Installer row);
}