package com.example.dao.mapper;

import com.example.model.entity.Merchant;
import com.example.model.entity.MerchantExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MerchantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchants
     *
     * @mbg.generated
     */
    long countByExample(MerchantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchants
     *
     * @mbg.generated
     */
    int deleteByExample(MerchantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchants
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer merchantid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchants
     *
     * @mbg.generated
     */
    int insert(Merchant row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchants
     *
     * @mbg.generated
     */
    int insertSelective(Merchant row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchants
     *
     * @mbg.generated
     */
    List<Merchant> selectByExample(MerchantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchants
     *
     * @mbg.generated
     */
    Merchant selectByPrimaryKey(Integer merchantid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchants
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") Merchant row, @Param("example") MerchantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchants
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") Merchant row, @Param("example") MerchantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchants
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Merchant row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchants
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Merchant row);
}