package com.example.dao.mapper;

import com.example.model.entity.PaymentInfo;
import com.example.model.entity.PaymentInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PaymentInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentinfo
     *
     * @mbg.generated
     */
    long countByExample(PaymentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentinfo
     *
     * @mbg.generated
     */
    int deleteByExample(PaymentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentinfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer paymentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentinfo
     *
     * @mbg.generated
     */
    int insert(PaymentInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentinfo
     *
     * @mbg.generated
     */
    int insertSelective(PaymentInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentinfo
     *
     * @mbg.generated
     */
    List<PaymentInfo> selectByExample(PaymentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentinfo
     *
     * @mbg.generated
     */
    PaymentInfo selectByPrimaryKey(Integer paymentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentinfo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") PaymentInfo row, @Param("example") PaymentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentinfo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") PaymentInfo row, @Param("example") PaymentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PaymentInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PaymentInfo row);
}