package com.example.model.entity;

public class Installer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column installers.InstallerID
     *
     * @mbg.generated
     */
    private Integer installerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column installers.Name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column installers.PhoneNumber
     *
     * @mbg.generated
     */
    private String phonenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column installers.UserName
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column installers.PassWord
     *
     * @mbg.generated
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column installers.InstallerID
     *
     * @return the value of installers.InstallerID
     *
     * @mbg.generated
     */
    public Integer getInstallerid() {
        return installerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column installers.InstallerID
     *
     * @param installerid the value for installers.InstallerID
     *
     * @mbg.generated
     */
    public void setInstallerid(Integer installerid) {
        this.installerid = installerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column installers.Name
     *
     * @return the value of installers.Name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column installers.Name
     *
     * @param name the value for installers.Name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column installers.PhoneNumber
     *
     * @return the value of installers.PhoneNumber
     *
     * @mbg.generated
     */
    public String getPhonenumber() {
        return phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column installers.PhoneNumber
     *
     * @param phonenumber the value for installers.PhoneNumber
     *
     * @mbg.generated
     */
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber == null ? null : phonenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column installers.UserName
     *
     * @return the value of installers.UserName
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column installers.UserName
     *
     * @param username the value for installers.UserName
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column installers.PassWord
     *
     * @return the value of installers.PassWord
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column installers.PassWord
     *
     * @param password the value for installers.PassWord
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}