package com.example.model.entity;

public class Merchant {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchants.MerchantID
     *
     * @mbg.generated
     */
    private Integer merchantid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchants.MerchantName
     *
     * @mbg.generated
     */
    private String merchantname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchants.MerchantAddress
     *
     * @mbg.generated
     */
    private String merchantaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchants.PhoneNumber
     *
     * @mbg.generated
     */
    private String phonenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchants.UserName
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchants.PassWord
     *
     * @mbg.generated
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchants.MerchantID
     *
     * @return the value of merchants.MerchantID
     *
     * @mbg.generated
     */
    public Integer getMerchantid() {
        return merchantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchants.MerchantID
     *
     * @param merchantid the value for merchants.MerchantID
     *
     * @mbg.generated
     */
    public void setMerchantid(Integer merchantid) {
        this.merchantid = merchantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchants.MerchantName
     *
     * @return the value of merchants.MerchantName
     *
     * @mbg.generated
     */
    public String getMerchantname() {
        return merchantname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchants.MerchantName
     *
     * @param merchantname the value for merchants.MerchantName
     *
     * @mbg.generated
     */
    public void setMerchantname(String merchantname) {
        this.merchantname = merchantname == null ? null : merchantname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchants.MerchantAddress
     *
     * @return the value of merchants.MerchantAddress
     *
     * @mbg.generated
     */
    public String getMerchantaddress() {
        return merchantaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchants.MerchantAddress
     *
     * @param merchantaddress the value for merchants.MerchantAddress
     *
     * @mbg.generated
     */
    public void setMerchantaddress(String merchantaddress) {
        this.merchantaddress = merchantaddress == null ? null : merchantaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchants.PhoneNumber
     *
     * @return the value of merchants.PhoneNumber
     *
     * @mbg.generated
     */
    public String getPhonenumber() {
        return phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchants.PhoneNumber
     *
     * @param phonenumber the value for merchants.PhoneNumber
     *
     * @mbg.generated
     */
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber == null ? null : phonenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchants.UserName
     *
     * @return the value of merchants.UserName
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchants.UserName
     *
     * @param username the value for merchants.UserName
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchants.PassWord
     *
     * @return the value of merchants.PassWord
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchants.PassWord
     *
     * @param password the value for merchants.PassWord
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}