package com.example.model.entity;

import java.math.BigDecimal;
import java.util.Date;

public class PaymentInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentinfo.PaymentID
     *
     * @mbg.generated
     */
    private Integer paymentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentinfo.OrderID
     *
     * @mbg.generated
     */
    private Integer orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentinfo.PaymentTime
     *
     * @mbg.generated
     */
    private Date paymenttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentinfo.PaymentMethod
     *
     * @mbg.generated
     */
    private String paymentmethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentinfo.PaymentAmount
     *
     * @mbg.generated
     */
    private BigDecimal paymentamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentinfo.PaymentStatus
     *
     * @mbg.generated
     */
    private String paymentstatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentinfo.PaymentID
     *
     * @return the value of paymentinfo.PaymentID
     *
     * @mbg.generated
     */
    public Integer getPaymentid() {
        return paymentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentinfo.PaymentID
     *
     * @param paymentid the value for paymentinfo.PaymentID
     *
     * @mbg.generated
     */
    public void setPaymentid(Integer paymentid) {
        this.paymentid = paymentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentinfo.OrderID
     *
     * @return the value of paymentinfo.OrderID
     *
     * @mbg.generated
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentinfo.OrderID
     *
     * @param orderid the value for paymentinfo.OrderID
     *
     * @mbg.generated
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentinfo.PaymentTime
     *
     * @return the value of paymentinfo.PaymentTime
     *
     * @mbg.generated
     */
    public Date getPaymenttime() {
        return paymenttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentinfo.PaymentTime
     *
     * @param paymenttime the value for paymentinfo.PaymentTime
     *
     * @mbg.generated
     */
    public void setPaymenttime(Date paymenttime) {
        this.paymenttime = paymenttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentinfo.PaymentMethod
     *
     * @return the value of paymentinfo.PaymentMethod
     *
     * @mbg.generated
     */
    public String getPaymentmethod() {
        return paymentmethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentinfo.PaymentMethod
     *
     * @param paymentmethod the value for paymentinfo.PaymentMethod
     *
     * @mbg.generated
     */
    public void setPaymentmethod(String paymentmethod) {
        this.paymentmethod = paymentmethod == null ? null : paymentmethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentinfo.PaymentAmount
     *
     * @return the value of paymentinfo.PaymentAmount
     *
     * @mbg.generated
     */
    public BigDecimal getPaymentamount() {
        return paymentamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentinfo.PaymentAmount
     *
     * @param paymentamount the value for paymentinfo.PaymentAmount
     *
     * @mbg.generated
     */
    public void setPaymentamount(BigDecimal paymentamount) {
        this.paymentamount = paymentamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentinfo.PaymentStatus
     *
     * @return the value of paymentinfo.PaymentStatus
     *
     * @mbg.generated
     */
    public String getPaymentstatus() {
        return paymentstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentinfo.PaymentStatus
     *
     * @param paymentstatus the value for paymentinfo.PaymentStatus
     *
     * @mbg.generated
     */
    public void setPaymentstatus(String paymentstatus) {
        this.paymentstatus = paymentstatus == null ? null : paymentstatus.trim();
    }
}