package com.example.model.entity;

import java.math.BigDecimal;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.ProductID
     *
     * @mbg.generated
     */
    private Integer productid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.ProductName
     *
     * @mbg.generated
     */
    private String productname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.MerchantID
     *
     * @mbg.generated
     */
    private Integer merchantid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.Price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.StockQuantity
     *
     * @mbg.generated
     */
    private Integer stockquantity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.ProductID
     *
     * @return the value of products.ProductID
     *
     * @mbg.generated
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.ProductID
     *
     * @param productid the value for products.ProductID
     *
     * @mbg.generated
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.ProductName
     *
     * @return the value of products.ProductName
     *
     * @mbg.generated
     */
    public String getProductname() {
        return productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.ProductName
     *
     * @param productname the value for products.ProductName
     *
     * @mbg.generated
     */
    public void setProductname(String productname) {
        this.productname = productname == null ? null : productname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.MerchantID
     *
     * @return the value of products.MerchantID
     *
     * @mbg.generated
     */
    public Integer getMerchantid() {
        return merchantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.MerchantID
     *
     * @param merchantid the value for products.MerchantID
     *
     * @mbg.generated
     */
    public void setMerchantid(Integer merchantid) {
        this.merchantid = merchantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.Price
     *
     * @return the value of products.Price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.Price
     *
     * @param price the value for products.Price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.StockQuantity
     *
     * @return the value of products.StockQuantity
     *
     * @mbg.generated
     */
    public Integer getStockquantity() {
        return stockquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.StockQuantity
     *
     * @param stockquantity the value for products.StockQuantity
     *
     * @mbg.generated
     */
    public void setStockquantity(Integer stockquantity) {
        this.stockquantity = stockquantity;
    }
}