package com.example.model.entity;

public class Review {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reviews.ReviewID
     *
     * @mbg.generated
     */
    private Integer reviewid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reviews.OrderID
     *
     * @mbg.generated
     */
    private Integer orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reviews.ReviewContent
     *
     * @mbg.generated
     */
    private String reviewcontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reviews.ReviewRating
     *
     * @mbg.generated
     */
    private Integer reviewrating;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reviews.ReviewID
     *
     * @return the value of reviews.ReviewID
     *
     * @mbg.generated
     */
    public Integer getReviewid() {
        return reviewid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reviews.ReviewID
     *
     * @param reviewid the value for reviews.ReviewID
     *
     * @mbg.generated
     */
    public void setReviewid(Integer reviewid) {
        this.reviewid = reviewid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reviews.OrderID
     *
     * @return the value of reviews.OrderID
     *
     * @mbg.generated
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reviews.OrderID
     *
     * @param orderid the value for reviews.OrderID
     *
     * @mbg.generated
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reviews.ReviewContent
     *
     * @return the value of reviews.ReviewContent
     *
     * @mbg.generated
     */
    public String getReviewcontent() {
        return reviewcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reviews.ReviewContent
     *
     * @param reviewcontent the value for reviews.ReviewContent
     *
     * @mbg.generated
     */
    public void setReviewcontent(String reviewcontent) {
        this.reviewcontent = reviewcontent == null ? null : reviewcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reviews.ReviewRating
     *
     * @return the value of reviews.ReviewRating
     *
     * @mbg.generated
     */
    public Integer getReviewrating() {
        return reviewrating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reviews.ReviewRating
     *
     * @param reviewrating the value for reviews.ReviewRating
     *
     * @mbg.generated
     */
    public void setReviewrating(Integer reviewrating) {
        this.reviewrating = reviewrating;
    }
}