spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/hbmssystem?useUnicode=true&characterSet=UTF-8&serverTimezone=Asia/Shanghai
        username: root
        password: 953306
